<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_pengumuman extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_pengumuman_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $admin_pengumuman = $this->Admin_pengumuman_model->get_all();

        $data = array(
            'admin_pengumuman_data' => $admin_pengumuman
        );

        $this->template->load('template','pengumuman_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Admin_pengumuman_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'judul_pengumuman' => $row->judul_pengumuman,
		'isi_pengumuman' => $row->isi_pengumuman,
		'link_file' => $row->link_file,
	    );
            $this->template->load('template','pengumuman_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin_pengumuman'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('admin_pengumuman/create_action'),
	    'id' => set_value('id'),
	    'judul_pengumuman' => set_value('judul_pengumuman'),
	    'isi_pengumuman' => set_value('isi_pengumuman'),
	    'link_file' => set_value('link_file'),
	);
        $this->template->load('template','pengumuman_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'judul_pengumuman' => $this->input->post('judul_pengumuman',TRUE),
		'isi_pengumuman' => $this->input->post('isi_pengumuman',TRUE),
		'link_file' => $this->input->post('link_file',TRUE),
	    );

            $this->Admin_pengumuman_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin_pengumuman'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Admin_pengumuman_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('admin_pengumuman/update_action'),
		'id' => set_value('id', $row->id),
		'judul_pengumuman' => set_value('judul_pengumuman', $row->judul_pengumuman),
		'isi_pengumuman' => set_value('isi_pengumuman', $row->isi_pengumuman),
		'link_file' => set_value('link_file', $row->link_file),
	    );
            $this->template->load('template','pengumuman_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin_pengumuman'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'judul_pengumuman' => $this->input->post('judul_pengumuman',TRUE),
		'isi_pengumuman' => $this->input->post('isi_pengumuman',TRUE),
		'link_file' => $this->input->post('link_file',TRUE),
	    );

            $this->Admin_pengumuman_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin_pengumuman'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Admin_pengumuman_model->get_by_id($id);

        if ($row) {
            $this->Admin_pengumuman_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin_pengumuman'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin_pengumuman'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('judul_pengumuman', 'judul pengumuman', 'trim|required');
	$this->form_validation->set_rules('isi_pengumuman', 'isi pengumuman', 'trim|required');
	$this->form_validation->set_rules('link_file', 'link file', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Admin_pengumuman.php */
/* Location: ./application/controllers/Admin_pengumuman.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-13 19:17:25 */
/* http://harviacode.com */